apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: denemeapp
spec:
  destination:
    namespace: deneme
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/yigitf/helm-argo-secret.git'
    targetRevision: v2
    chart: helm01
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
